### ISSUE TITLE
Ring adapter

### ISSUE THREAD

**Issue by cgrand** [portkey-cloud/portkey#32]
Mount any Ring app as a lambda. Depends on #31

**Comment by viesti** [comment]
Some prior art found here https://github.com/jpb/ring-aws-lambda-adapter/blob/master/src/ring_aws_lambda_adapter/core.clj

**Comment by viesti** [comment]
First version now in master with `pk/mount-ring!`

**Comment by viesti** [comment]
`pk/mount-ring!` is now a macro (added in b4a8c80fe114255f652d9f1339a16d50dac9cdb6), like `pk/mount!` so can accept a symbol. Closing this now, any bugs belong to new issues :)
