### ISSUE TITLE
boot, portkey, transit-clj issue

### ISSUE THREAD

**Issue by qq00** [portkey-cloud/portkey#38]
## high level overview

I can't get boot, transit-clj, and portkey to work together

It appears 'cheshire' and jackson-xml may also be involved.

## error

$ boot repl
nREPL server started on port 35137 on host 127.0.0.1 - nrepl://127.0.0.1:35137
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0-alpha17
OpenJDK 64-Bit Server VM 1.8.0_144-b01
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
boot.user=> (require 'portkey.core)
Preparing for self instrumentation.
Ouroboros succesfully eating its own tail!
Instrumenting clojure.lang.Var... done!

boot.user=>        java.lang.ClassNotFoundException: com.fasterxml.jackson.core.FormatFeature
         java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/FormatFeature
clojure.lang.Compiler$CompilerException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/FormatFeature, compiling:(cheshire/factory.clj:53:5)

## build.boot I am using:

(set-env!
 :source-paths #{"src"} 
 :resource-paths #{"resources/"}
 :dependencies '[;; clojure core 
                 [org.clojure/clojure "1.9.0-alpha17"] 
                 [com.cognitect/transit-clj "0.8.297"] 
                 [portkey "0.1.0-SNAPSHOT"]
                 ]) 

## aside

if I remove the transit-clj line, (require 'portkey.core) works fine.

If I remove the oprtkey line, transit-clj also loads fine.

**Comment by qq00** [comment]
this issue appears to go away when I update to 

transit-clj "0.8.300"

closing

**Comment by cgrand** [comment]
I guess you had a latent version conflict that pottery triggered.
