### ISSUE TITLE
S3 upload

### ISSUE THREAD

**Issue by cgrand** [portkey-cloud/portkey#9]
Upload Lambda package to S3 and pass bucket/key to UpdateFunctionCode (http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html#SSS-UpdateFunctionCode-request-S3Bucket)

**Comment by viesti** [comment]
Haa, I think this got into master in 712224947d9ae50a7e4af888076b6048bd9895d3.

**Comment by viesti** [comment]
`deploy!` takes now a map under`:s3` key with `:bucket` and `:key` keys. `:key` is optional, defaults to `(str lambda-function-name ".zip")`.
